### ISSUE TITLE
Push Notification 

### ISSUE THREAD

**Issue by JebHunt** [fumc-pensacola/satellite#6]
Error message received when trying to send a push notification in mission control. Error Message: 
<img width="451" alt="screen shot 2015-11-07 at 8 34 30 pm" src="https://cloud.githubusercontent.com/assets/12077563/11018450/35031976-858f-11e5-85ba-cf4c6fa6c93d.png">
Notification failed to save to server. Will not send.

**Comment by andrewbranch** [comment]
Closing because notification support is discontinued for now. Need to remove the endpoints and model.
